1062 onvista account statement support (minor)
tresorone/tresor-import pull request #1072
Opened 2021-01-18 19:11 UTC by SirGibihm

Added partial support for onvista account statements. 
* Fixes #1062 
* Fixes #636

2021-01-23 06:39 UTC, dredav requested changes

2021-01-23 06:39 UTC, dredav commented on src/brokers/onvista.js
> +  const searchTerms = ['Wertpapierkauf'];
The first (and last) stock I've sell was in my onvista depot in 2016. I'll anonymize the document to add also sell support. And also I've got some dividends from ETFs too.

2021-01-23 06:39 UTC, dredav commented on tests/helper/index.test.js
> +  describe('findNextLineIndexByRegex is working as intended', () => {
I would prefer also a test with the offset parameter

2021-01-23 09:13 UTC, dredav commented on src/brokers/onvista.js
> +  const searchTerms = ['Wertpapierkauf'];
I added #1146 with the the documents and assigned it to you @SirGibihm.

2021-01-23 10:02 UTC, SirGibihm commented on tests/helper/index.test.js
> +  describe('findNextLineIndexByRegex is working as intended', () => {
Added

2021-01-23 13:51 UTC, SirGibihm commented on src/brokers/onvista.js
> +  const searchTerms = ['Wertpapierkauf'];
I integrated those files into the tests and adjusted the code.

2021-01-24 10:13 UTC, dredav commented on docs/implementations.md
> +| onvista                | Buy, Sell, Dividend, Account Statements (Buy and Sell Only) | Account Statements need more testfiles for Sell and Dividend transactions          |
Dividends are alreadt implemented, right?

2021-01-24 20:25 UTC, SirGibihm commented on docs/implementations.md
> +| onvista                | Buy, Sell, Dividend, Account Statements (Buy and Sell Only) | Account Statements need more testfiles for Sell and Dividend transactions          |
Yes, corrected this

2021-01-25 04:28 UTC, dredav approved these changes

2021-01-25 04:31 UTC, merged