[trade republic] Fix parsing of quarter statement Q4/2020
tresorone/tresor-import pull request #1324
Opened 2021-01-28 04:30 UTC by dredav

- Add testcase from #1188
- Fix #1188: Now we can parse the changed number format and also that sometimes the number of shares are above the line `Stk.`

2021-01-28 09:22 UTC, SirGibihm requested changes

2021-01-28 09:22 UTC, SirGibihm commented on src/brokers/traderepublic.js
> +  const numberOfShares = parseGermanNum(numberOfSharesLine.replace('.', ','));
I do think this is a bad idea for the following reason:
If you cast this on a full German number format you will receive an illegitimate number:
`3.133,7` would become `3,133,7`. The testcases did not fail as there is no example where more than 1k stocks were listed. IMO we should implement a check wether the number contains a `.` and a `,` but this still leaves another issue: What about German round numbers: `1.337(,00)`. They would be parsed to equal `1,337`

2021-01-28 20:05 UTC, dredav commented on src/brokers/traderepublic.js
> +  const numberOfShares = parseGermanNum(numberOfSharesLine.replace('.', ','));
Yes, this part is a pretty bad solution. I've checked your samples and currently only one position has more than 999 shares: https://github.com/tresorone/tresor-import/blob/7c3a40a2370caa97eb782b970ad122eeedec6b91/tests/brokers/__mocks__/traderepublic/quarter_statement/2020_year_end_statement.json#L68

I will adjust this logic to be a little bit safer on the road:
- Check if `numberOfSharesLine` contains a `,`, then don't replace the `.`
- Add the 1000 shares position as an additional test case

2021-01-29 08:49 UTC, SirGibihm approved these changes

2021-01-29 08:49 UTC, merged