[Onvista] Added a new type of file that shall not be parsed
tresorone/tresor-import pull request #1601
Opened 2021-02-10 20:51 UTC by SirGibihm

Added the Storno files from #1600.
However, I could not make sense of one of the files provided by the user. Asked dredav for his view on things

2021-02-24 20:53 UTC, dredav commented
@SirGibihm Is this PR ready for review? It's since 14 days a draft.

2021-02-25 12:09 UTC, dredav requested changes

2021-02-25 12:09 UTC, dredav commented on src/brokers/onvista.js
> +    console.log(1)
This can also be removed.

2021-03-02 19:14 UTC, SirGibihm commented on src/brokers/onvista.js
> +    console.log(1)
Fixed

2021-03-02 19:30 UTC, dredav approved these changes

2021-03-02 19:31 UTC, merged