[ovnista] Smartbroker overhaul (minor)
tresorone/tresor-import pull request #1735
Opened 2021-02-22 22:22 UTC by SirGibihm

- Added a new ignored document Fixes #1721 
- Overhauled fee-Parsing in Mother-script #1713

2021-02-22 23:53 UTC, SirGibihm commented
This is still a draft. Can’t convert to draft from mobile so it’s not marked as such

2021-02-23 16:14 UTC, dredav requested changes

2021-02-23 16:49 UTC, SirGibihm commented on src/helper/index.js
> +  time = undefined,
No problem, I can remove it if you want. I often see myself sending a dedicated `undefined` which clutters the code though. The issue you mention should be caught during the review process imo, not in the code

2021-02-23 16:49 UTC, SirGibihm commented on tests/brokers/__mocks__/smartbroker/sell/2021_turbo_knockout.json
> +    "DEPOTNUMMER=5180302001",
Fixed

2021-02-23 16:49 UTC, SirGibihm commented on tests/brokers/__mocks__/smartbroker/sell/2021_turbo_knockout.json
> +    "ADRESSZEILE2=Felix-Benjamin Schwermer",
Fixed

2021-02-24 20:40 UTC, dredav commented on src/helper/index.js
> +  time = undefined,
hmm your right. We do a review for all changes, so it's fine for me.

2021-02-24 20:41 UTC, dredav approved these changes

2021-02-24 20:42 UTC, merged