Commerzbank dividenden
tresorone/tresor-import pull request #1740
Opened 2021-02-23 15:38 UTC by oxi0

Entered new logics for dividends and added testcases.

This solves #824 #827 #915

2021-02-24 07:51 UTC, oxi0 commented
@SirGibihm I noticed that the functions in the sell area all uses the buy functions. Should the function names be adapted to BuySell as in the last pull request?

2021-02-24 09:08 UTC, SirGibihm commented
> 
> 
> @SirGibihm I noticed that the functions in the sell area all uses the buy functions. Should the function names be adapted to BuySell as in the last pull request?

Combining functions does make sense as long as it reduces code duplication and code clutter. So yeah, the make it BuySells

2021-02-24 21:32 UTC, dredav requested changes

2021-02-24 21:32 UTC, dredav commented on src/brokers/commerzbank.js
> +	if (textArr[textArr.findIndex(t => t.includes('per')) + 1].split(".").length > 1) {
Did you run the eslint pre-commit hock at commit? The hock will fix this automatically

```suggestion
	if (textArr[textArr.findIndex(t => t.includes('per')) + 1].split('.').length > 1) {
```

2021-02-24 21:32 UTC, dredav commented on src/brokers/commerzbank.js
> +	    isinIdx = textArr.findIndex(t => t.includes('Inhaber-Anteile')) - 1;
So you are checking `indexOf('Inhaber-Anteile')` and then searching for a line that is not equal `Inhaber-Anteile` and only contains `Inhaber-Anteile`. Whats abot this pseudo code:
cost lineNumber = textArr.findIndex(t => t.includes('Inhaber-Anteile'));
if (lineNumber >= 0) { isinIdx = lineNumber - 1}

2021-02-24 21:32 UTC, dredav commented on src/brokers/commerzbank.js
> +	    isinIdx = textArr.findIndex(t => t.includes('Inhaber-Anteile')) - 1;
Same thing at L85-86

2021-02-24 21:32 UTC, dredav commented on src/brokers/commerzbank.js
> +    return +Big(parseGermanNum(textArr[textArr.findIndex(t => t.includes('Minimumprovision')) + 3]));
Also the `indexOf`/`includes` thing.

2021-02-24 21:32 UTC, dredav commented on src/brokers/commerzbank.js
> +      return textArr.slice(startCompanyName, startCompanyName + 2).join(' ');
Also the `indexOf`/`includes` thing.

2021-02-24 21:32 UTC, dredav commented on tests/brokers/commerzbank.test.js
> +        company: 'LD',
This should be `DWS TOP DIVIDENDE LD`

2021-02-24 21:32 UTC, dredav commented on tests/brokers/commerzbank.test.js
> +        tax: 0,
The withholding tax is missing here.

2021-02-24 21:32 UTC, dredav commented on tests/brokers/commerzbank.test.js
> +        amount: 15.71,
The amount shoud be gross including the withholding tax. This also affect the price per share.

2021-02-24 21:32 UTC, dredav commented on tests/brokers/commerzbank.test.js
> +        datetime: '2020-12-23T' + result.activities[0].datetime.substring(11),
Could you add here the full date static? The time should be 12:36.

2021-02-24 21:32 UTC, dredav commented on src/brokers/commerzbank.js
>    } else {
Minor: I would like to reduce the indents. This can be converted to a `else if`.

2021-02-25 09:55 UTC, oxi0 commented on src/brokers/commerzbank.js
> +	if (textArr[textArr.findIndex(t => t.includes('per')) + 1].split(".").length > 1) {
Fixed

2021-02-25 10:10 UTC, oxi0 commented on src/brokers/commerzbank.js
> +	    isinIdx = textArr.findIndex(t => t.includes('Inhaber-Anteile')) - 1;
Looks better, thanks for the note. 
Fixed

2021-02-25 10:18 UTC, oxi0 commented on src/brokers/commerzbank.js
> +    return +Big(parseGermanNum(textArr[textArr.findIndex(t => t.includes('Minimumprovision')) + 3]));
Fixed

2021-02-25 10:29 UTC, oxi0 commented on src/brokers/commerzbank.js
> +      return textArr.slice(startCompanyName, startCompanyName + 2).join(' ');
Fixed

2021-02-25 10:31 UTC, oxi0 commented on tests/brokers/commerzbank.test.js
> +        company: 'LD',
I had already noticed that, but the document only offers this name. The full name appears to be missing here and only this shortcut is given.

2021-02-25 11:56 UTC, oxi0 commented on tests/brokers/commerzbank.test.js
> +        tax: 0,
Fixes

2021-02-25 12:06 UTC, dredav commented on tests/brokers/commerzbank.test.js
> +        company: 'LD',
The name is written some lines above (before the number of shares). Is is possible to have a smart logic to match them also?

2021-02-25 12:12 UTC, oxi0 commented on tests/brokers/commerzbank.test.js
> +        amount: 15.71,
This behavior seems to have been implemented this way for a long time. I have now adjusted the logic, but had to change three old test cases. I hope that was okay. The changes looked okay to me.

2021-02-25 12:15 UTC, oxi0 commented on tests/brokers/commerzbank.test.js
> +        datetime: '2020-12-23T' + result.activities[0].datetime.substring(11),
Fixed

2021-02-25 12:21 UTC, oxi0 commented on src/brokers/commerzbank.js
>    } else {
Fixed

2021-02-25 12:49 UTC, oxi0 commented on tests/brokers/commerzbank.test.js
> +        company: 'LD',
Okay, I missed that. The logic has been adjusted.

2021-03-02 19:00 UTC, SirGibihm commented on tests/brokers/commerzbank.test.js
> +        amount: 15.71,
Bugs such as these are to be expected in our codebase ^^'
Thanks for fixing it!

2021-03-02 19:01 UTC, SirGibihm commented
@oxi0 Looking good, merging! Sorry it took us some time to review. Real life sometimes gets in the way

2021-03-02 19:05 UTC, SirGibihm approved these changes
Looking good, all requests by @dredav have been handled. @dredav Could you mark your changes as resolved if you agree? I can take care of merging

2021-03-02 19:28 UTC, merged

2021-03-07 11:30 UTC, oxi0 commented
Thank you for accepting the merge request. 
I noticed that the tickets are still open. Can you fix it @SirGibihm or @dredav?

2021-03-07 11:48 UTC, dredav commented
Oh yes, I've closed the issues. The issues wasn't closed automatically because the issues wasn't linked to this PR.  /cc @SirGibihm