[generel] Added a Licensing Model for the Importer (major)
tresorone/tresor-import pull request #1741
Opened 2021-02-23 15:58 UTC by SirGibihm

The importer shall be run unter the AGLv3 License. This should be checked + verified by @codeofsumit and @dredav

2021-02-23 16:33 UTC, codeofsumit requested changes
Great great great!!!

2021-02-23 16:33 UTC, codeofsumit commented on README.md
> +  - Modify and distribute the Codebase in any way ou want
```suggestion
  - Modify and distribute the codebase in any way you want
```

2021-02-23 16:33 UTC, codeofsumit commented on README.md
> +- You are allowed to:
```suggestion
- You are permitted to:
```

2021-02-23 16:33 UTC, codeofsumit commented on README.md
> +**THIS PARAGRAPH GIVES ONLY AN INCOMPLETE AND ROUGH OVERVIEW. READ THE LICENSE BEFORE USING**
```suggestion
**HERE'S AN INCOMPLETE SUMMARY. READ THE FULL LICENSE BEFORE USING**
```

2021-02-23 16:33 UTC, codeofsumit commented on README.md
> +  - respect the Copyright which is held by the maintainers of this project
```suggestion
  - respect the copyright which is held by the maintainers of this project
```

2021-02-23 16:33 UTC, codeofsumit commented on README.md
> +  - You MUST disclose all changes you made to the code and also publish any code directly based on this code
```suggestion
  -  disclose all changes you made to the code and also publish any code directly based on this code
```

2021-02-23 16:33 UTC, codeofsumit commented on README.md
> +  - You MUST give attribution to the orignal maintainers when using this project (especially when used commercially)
```suggestion
  - give attribution to the orignal maintainers when using this project (especially when used commercially)
```

2021-02-23 16:33 UTC, codeofsumit commented on README.md
> +  - expect any Liability, Warranty or similar by the original Maintainers. However, we want to improve
```suggestion
  - expect any liability, warranty or similar by the original maintainers. However, we want to improve
```

2021-02-23 16:33 UTC, codeofsumit commented on README.md
> +**THIS PARAGRAPH GIVES ONLY AN INCOMPLETE AND ROUGH OVERVIEW. READ THE LICENSE BEFORE USING**
Let's add a link here to the full license.

2021-02-23 16:33 UTC, codeofsumit commented on LICENSE
> +<https://www.gnu.org/licenses/>.
😍  amazing!

2021-02-23 16:45 UTC, SirGibihm commented
@dredav I implemented Sumits change requests. If you don't find anything you would like to see changed please merge

2021-02-24 20:49 UTC, dredav commented on README.md
> +See also the following image, taken from [TL;DR Legal](https://www.tldrlegal.com/l/agpl3).
Oh nice service. Good to know it.

2021-02-24 20:49 UTC, dredav commented on README.md
> +**HERE'S AN INCOMPLETE SUMMARY. READ THE [FULL LICENSE](LICENSE) BEFORE USING**
I thinks it's better to add a new line for a better readability.

```suggestion

**HERE'S AN INCOMPLETE SUMMARY. READ THE [FULL LICENSE](LICENSE) BEFORE USING.**
```

2021-02-24 20:50 UTC, dredav reviewed
Could you also change the license in the `package.json`?

2021-02-24 20:51 UTC, dredav commented on README.md
> +  - respect the copyright which is held by the maintainers of this project
Also I would recomend to start each point with an capital letter

2021-02-24 20:52 UTC, dredav commented
This is a great and important change! Thanks for adressing it @SirGibihm. I only requested some minor changes.

2021-02-24 22:25 UTC, SirGibihm commented
@dredav Worked in your comments, especially the ones regarding the package-lock

2021-02-25 12:01 UTC, dredav approved these changes

2021-02-25 12:02 UTC, dredav approved these changes

2021-02-25 12:03 UTC, dredav commented
Mergin is blocked because @codeofsumit has requested changes previously. Waiting for a second approval.

2021-02-25 12:23 UTC, codeofsumit approved these changes

2021-02-25 12:48 UTC, merged

2021-02-26 07:09 UTC, carstenhag commented
Nice move, I think the AGPL is a good fit.  

FYI though, tresor.one, import.tresor.one etc must now disclose the usage of this lib :)