[degiro]  Adding support for depot statements based on #1742
tresorone/tresor-import pull request #1749
Opened 2021-02-24 10:32 UTC by SirGibihm

Adding support for Depot statements
- Added Testcases:
  - Fixes #1742
- Checked locally using localhost:5000
  -

2021-03-02 20:01 UTC, dredav commented
@SirGibihm Is this PR ready for review?

2021-03-02 20:44 UTC, SirGibihm commented
> 
> 
> @SirGibihm Is this PR ready for review?

I am still working on some more degiro issues to be integrated within this PR so no, not yet

2021-03-27 13:45 UTC, dredav requested changes
Looks good, found one small issue with foreign languages.

2021-03-27 13:45 UTC, dredav commented on src/brokers/degiro.js
> +    /(DEGIRO B\.V\. ist als)|\d{2}-\d{2}-\d{4}/,
We should remove the German `ist als` to support the other language documents (e.g. IT https://github.com/tresorone/tresor-import/blob/58a456040ee29c24b2a3c3c42438e4a53a49e220/tests/brokers/__mocks__/degiro/transactionLog/buy_only_transactions_it.json#L102)

2021-03-27 13:45 UTC, dredav commented
Can you also resolve the conflicts?

2021-03-27 13:46 UTC, dredav commented
@Zemmor Do you have a portfolio statement from degio in italian language that we can add as a seconds test case for this PR?

2021-03-27 16:04 UTC, Zemmor commented on src/brokers/degiro.js
> +        line.startsWith('Portfolioübersicht per ')
for Italian File:  "Panoramica Portafoglio al"

2021-03-27 16:07 UTC, Zemmor commented
@dredav I found that Isssue in the project: https://github.com/tresorone/tresor-import/issues/2149

If you want another one, I can also Upload a portfolio statement file

2021-04-13 04:22 UTC, dredav approved these changes

2021-04-13 04:23 UTC, merged