[onvista] Add support to parse a portfolio statement
tresorone/tresor-import pull request #196
Opened 2020-10-31 17:18 UTC by dredav

- Add test case from #148 
- Add activity type `TransferIn` (Einlieferung) to function `validateActivity`
- Fix #148

2020-11-02 13:23 UTC, codeofsumit submitted a review, later dismissed
Ok nice!

`TransferIn` and `TransferOut` are not yet supported in the T1 codebase but I will work on it. Will merge this PR as soon as that's done

2020-12-02 20:46 UTC, SirGibihm submitted a review, later dismissed

2020-12-02 21:09 UTC, dredav commented on src/brokers/onvista.js
> +        },
My portfolio statement (it's my long term ETF portfolio) and the test files only contains the amount in EUR. So I'm not sure but onvista is a german bank and all orders are billed in EUR.

2020-12-02 21:09 UTC, dredav commented on src/brokers/onvista.js
> +  );
Good point, I will merge master into this!

2020-12-02 21:45 UTC, SirGibihm commented
@codeofsumit Not wanting to stress you but are `TransferIn` and `TransferOut` allready supported in the backend? Lots of new requests are comming in that require those.

2020-12-03 12:11 UTC, SirGibihm requested changes

2020-12-03 12:11 UTC, SirGibihm commented on src/brokers/onvista.js
> +          date: parsedDate,
Why choose type: `TransferIn` over `Buy`? I honestly don't know what to use where

2020-12-03 12:11 UTC, SirGibihm commented on src/helper/index.js
> +    }
As far as I can see, it is now finally allowed that fee and tax are left empty, do I get this right? Nice change! One question though: Why go the extra mile and add parameter `missingFeeAndTax = false`? Wouldn't it be enought to just accept `undefined` as a value for `tax` and `fee`?

2020-12-03 12:11 UTC, SirGibihm commented on src/brokers/onvista.js
> +          company: content[tableStartLine + 2],
While it is not completely necessary I guess, I would like to see the WKN being parsed as well

2021-01-03 11:20 UTC, SirGibihm commented
Oh and we got some merge conflicts. yay

2021-01-27 19:25 UTC, dredav commented on src/helper/index.js
> +    }
I removed this code - we don't need it longer.

2021-01-27 19:25 UTC, dredav commented on src/brokers/onvista.js
> +          company: content[tableStartLine + 2],
Yes. I added the wkn parsing.

2021-01-27 19:26 UTC, dredav commented on src/brokers/onvista.js
> +          date: parsedDate,
I choose `TransferIn` instead of `Buy` because we don't know the real buy prices. This is the besser way for this IMO, because we only import the current state of the statement.

2021-01-27 19:27 UTC, dredav commented on src/brokers/onvista.js
> +
Yes. I added a comment.

2021-01-27 19:27 UTC, dredav commented
Puh, what a merge... Conflicts solved.

2021-01-28 09:25 UTC, SirGibihm approved these changes

2021-01-28 09:26 UTC, merged