[Scalable/BaaderBank] ISIN with new layout, code refactoring (Fix #2602) (minor)
tresorone/tresor-import pull request #2614
Opened 2021-04-22 08:35 UTC by SirGibihm

* Fixes #2602 (ISIN comes in a new format; split across two lines instead of only in one line
* Code refactoring to lessen code volume

2021-04-22 14:37 UTC, dredav requested changes

2021-04-22 14:37 UTC, dredav commented on tests/brokers/__mocks__/baaderbank/buy/2021_scalable_adidas_ag.json
> +    "Stamm-Nr.: 1292047    Portfolio: 1",
Not sure if this is a personal number... can you remove it? Better save than sorry.

2021-04-25 18:55 UTC, SirGibihm commented on tests/brokers/__mocks__/baaderbank/buy/2021_scalable_adidas_ag.json
> +    "Stamm-Nr.: 1292047    Portfolio: 1",
Good catch. I fixed it

2021-04-27 03:19 UTC, dredav approved these changes

2021-04-27 03:20 UTC, merged