[FFB] Add pdf support for buy, sell, dividend, reinvest and service fee
tresorone/tresor-import pull request #3764
Opened 2021-08-22 19:51 UTC by Habemus42

Hi,
I'm trying to add support for FIL Fondsbank (FFB).
It's been a little tricky since the distances of the relevant lines depend on the document type or fund currency.
Moreover the broker sometimes issues collective bills, which contain multiple transactions.
I managed to add pdf support for buy and sell orders either in single bills or collective bills and for dividend payouts.
Dividend reinvest documents are issued as "Wiederanlage".
Service fee bills are called "Engeltbelastung". Here securities are sold to cover fees. 
I hope the pdfs I've used are not outdated.

2021-08-30 18:58 UTC, dredav commented
Thanks for your PR. I will start with the review this week.

2021-09-02 19:38 UTC, dredav requested changes
Thanks for you PR and taking case of FBB docuemnts. I've comment some advices to make you logic more resilient agains small changes. Also I would recomend to run prettier once (npm run lint).

2021-09-02 19:38 UTC, dredav commented on tests/brokers/__mocks__/ffb/index.js
> +multipleTransactions
Can you add here all samples from above?

2021-09-02 19:38 UTC, dredav commented on src/brokers/ffb.js
> +      content[lineNumber]==="Kauf aus Tausch" || content[lineNumber]==="Verkauf aus Tausch"  ||
I guess thats can be simplyfied with two `.startsWith()` eg. `content[lineNumber].startsWith('Kauf')`

2021-09-02 19:38 UTC, dredav commented on src/brokers/ffb.js
> +  } else if (content.includes('Ausschüttungsanzeige')) {
Is `Ausschüttungsanzeige` missing at the section with the transactionCounter?

2021-09-02 19:38 UTC, dredav commented on src/brokers/ffb.js
> +const getDocumentType = content => {
It looks like some duplicate code inside this function. I would recomend multiple counter for your case: buyTransactions, sellTransaction, ... . Than you can check if the sum of all counters is > 1 => multi. If not you can check each counter and then return the type (so you dont need to check again all lines for eg. containing `Kauf`

2021-09-02 19:38 UTC, dredav commented on src/brokers/ffb.js
> +  //older documents don't contain the identification string "FFB", so "FIL" is also needed
Good comment. It helps to unterstand whats FIL means.

2021-09-02 19:38 UTC, dredav commented on src/brokers/ffb.js
> +  return [textArr[buySellIndex+10], textArr[buySellIndex+8]];
Can you all some comments to all the `textArr[buySellIndex+10]` which line content is expected? I mean here its clear, ISIN in +10 and WKN in + 8 but whats in +5 at function findDateBuySell?

2021-09-02 19:38 UTC, dredav commented on src/brokers/ffb.js
> +    return +Big(parseGermanNum(textArr[buySellIndex+30])).plus(Big(parseGermanNum(textArr[buySellIndex+33])));
Whats behind the line numbers? Is it not easier to search for `Kapitalerstagsteuer`? Like you did for dividends? When yes, all types can call `findTax`. Can you also add support for church tax (like in #668)

2021-09-02 19:38 UTC, dredav commented on src/brokers/ffb.js
> +		if (textArr[buySellIndex+35]!=="Transaktionskosten") {
You are relying multiple times on hardcoded line numbers. It would be more flexible to check for the indexOf('Transaktionskosten') - so a new line can added above the `Transaktionskosten` location without breaking the full logic here.

2021-09-02 19:38 UTC, dredav commented on src/brokers/ffb.js
> +  [activity.date, activity.datetime] = createActivityDateTime(date, "12:00");
you can set the time to undefined - createActivityDateTime will handle that case for you.

2021-12-13 15:08 UTC, Habemus42 commented on tests/brokers/__mocks__/ffb/index.js
> +multipleTransactions
Done

2021-12-13 15:08 UTC, Habemus42 commented on src/brokers/ffb.js
> +      content[lineNumber]==="Kauf aus Tausch" || content[lineNumber]==="Verkauf aus Tausch"  ||
Done.

2021-12-13 15:10 UTC, Habemus42 commented on src/brokers/ffb.js
> +  } else if (content.includes('Ausschüttungsanzeige')) {
transactionCounter isn't necessary after ffb.js rewrite, now all documents except dividend statements are processed like multi-documents, so we don't have to differentiate between multi and single documents

2021-12-13 15:10 UTC, Habemus42 commented on src/brokers/ffb.js
> +const getDocumentType = content => {
see comment above

2021-12-13 16:16 UTC, Habemus42 commented on src/brokers/ffb.js
> +  return [textArr[buySellIndex+10], textArr[buySellIndex+8]];
done

2021-12-13 21:22 UTC, Habemus42 commented on src/brokers/ffb.js
> +    return +Big(parseGermanNum(textArr[buySellIndex+30])).plus(Big(parseGermanNum(textArr[buySellIndex+33])));
findTax() now searches for "Kapitalertragssteuer", "Solidaritätszuschlag", "Kirchensteuer" and reads the value in the line below.

2021-12-13 21:23 UTC, Habemus42 commented on src/brokers/ffb.js
> +		if (textArr[buySellIndex+35]!=="Transaktionskosten") {
done

2021-12-13 21:25 UTC, Habemus42 commented on src/brokers/ffb.js
> +  [activity.date, activity.datetime] = createActivityDateTime(date, "12:00");
I don't like changing that, since I remember running in some issues with my test files because of daylight saving time.

2021-12-13 21:29 UTC, Habemus42 commented
thanks for your review and sorry for the delay. I will add the code changes to the pull request tommorow.

2021-12-26 18:33 UTC, dredav requested changes
Looks good 🚀. Thanks for rewriting the implementation. I've only found some small thinks we should correct before merging this PR

2021-12-26 18:33 UTC, dredav commented on src/brokers/ffb.js
> +  return dateLine.match(/[0-9]{2}.[0-9]{2}.[1-2][0-9]{3}/)[0];
here you can use the helper function `getGermanDate`.

2021-12-26 18:33 UTC, dredav commented on src/brokers/ffb.js
> +			fee = parseGermanNum(textArr[startLine+line+1]);
Abter the fee was fount, isn't it better to leave the loop with a `break`?

2021-12-26 18:33 UTC, dredav commented on src/brokers/ffb.js
> +  if (type === 'Unsupported') {
We should also handle here the return type `undefined` of `getDocumentType` right?

2021-12-29 21:38 UTC, Habemus42 commented on src/brokers/ffb.js
> +  return dateLine.match(/[0-9]{2}.[0-9]{2}.[1-2][0-9]{3}/)[0];
Done.

2021-12-29 21:38 UTC, Habemus42 commented on src/brokers/ffb.js
> +			fee = parseGermanNum(textArr[startLine+line+1]);
Done.

2021-12-29 21:46 UTC, Habemus42 commented on src/brokers/ffb.js
> +  if (type === 'Unsupported') {
I think it isn't necessary to handle type = undefined in parsePages()! 
comdirect.js for example doesn't handle the undefined type in its parsePages() as well.

The way I understand it, if getDocumentType() returns undefined in the first place, canParseDocument() returns false and parsePages() won't be called.

2022-01-02 20:35 UTC, dredav submitted a review, later dismissed
🚀

2022-01-02 20:47 UTC, dredav approved these changes
I've added a docs entry and run prettier for both files `npx prettier src/brokers/ffb.js --write` and `npx prettier tests/brokers/ffb.test.js --write`.

2022-01-02 20:48 UTC, merged

2022-01-02 20:49 UTC, dredav commented
Thanks for your time and contributions to our import projekt @Habemus42!