build: applied types to index.js
tresorone/tresor-import pull request #3816
Opened 2021-08-30 22:00 UTC by tobiasdrechsel

Hi,
this PR is mainly intended to showcase the possible next steps after #3762 is merged. 
Although this would be ready to merge now I will keep it in draft mode until the other PR has landed (feel free to remove the draft status).

This is just the first of multiple iterations. I tried to keep the size of the PR reasonable.

The interfaces in [`custom.d.ts`](types/custom.d.ts) are not complete yet and will be extended with the next iterations. The interface definition is guided by the current implementation + docs.

From my point of view extensive typing adds a lot of value in regards of maintainability to the library. It can also significantly improve the implementation speed for changed/new brokers.

2021-08-31 11:52 UTC, tobiasdrechsel commented
@dredav this one would also be ready (provided #3762 is merged)

2021-09-12 23:35 UTC, JohnBra commented on types/custom.d.ts
>  export enum ParserStatus {
@tobiasdrechsel there are two small typos in `ParserStatus` enum:
`UNSUPORTED_FILETYPE` should be `UNSUPPORTED_FILETYPE`
`INVALID_DICUMENT` should be `INVALID_DOCUMENT`

2021-09-13 01:53 UTC, JohnBra commented
I think types and testing dependencies could be added already as well

- @types/node
- @types/jest
- @types/luxon
- ...

2021-09-13 15:22 UTC, tobiasdrechsel commented on types/custom.d.ts
>  export enum ParserStatus {
Done, thanks!

2021-09-13 15:31 UTC, tobiasdrechsel commented
> I think types and testing dependencies could be added already as well
> 
> @types/node
> @types/jest
> @types/luxon
> ...
 
@JohnBra 
Sure, I am planning many more contributions. I just thought it would make the review a little bit easier if the size of the PR is not too big. 
If you wish I can extend this PR!  

Other thinks that I would like to improve include:
- apply strong typing (the goal is to enable `strict` mode in `tsconfig.json`)
- update deps (I already started with #3881 )
- emit types and add them to the release (+ `package.json`) to improve DX for dependent projects

2021-09-21 09:33 UTC, dredav requested changes
Thanks for this PR! 

>This is just the first of multiple iterations. I tried to keep the size of the PR reasonable.

This is awesome.
I found some small issues.

Do you have a account in our community? I would like to discuss the next iterations with our, so can you send [me](https://community.parqet.com/u/e1ecc036) a message.

2021-09-21 09:33 UTC, dredav commented on types/custom.d.ts
> +  foreignCurrency?: number | string;
Is there any case there `foreignCurrency` is a number? This should be always a 3 letter string or undefined.

2021-09-21 09:33 UTC, dredav commented on types/custom.d.ts
> +  fxRate?: number | string;
Same as `foreignCurrency` but the fxRate should always a number or undefined.

2021-09-21 09:33 UTC, dredav commented on src/helper/index.js
> +  //TODO: the trimAndSplit coudl be removed and typeof content used to decide weather we need to enter this branch
small typo
```suggestion
  //TODO: the trimAndSplit could be removed and typeof content used to decide weather we need to enter this branch
```

2021-09-21 09:33 UTC, dredav commented on src/brokers/deutschebank.js
> + * @param {*} activityType
Type is `ActivityTypeUnion`

2021-09-24 09:28 UTC, tobiasdrechsel commented
> This is awesome.
> I found some small issues.

Thanks, I will resolve them right now

> Do you have a account in our community? I would like to discuss the next iterations with our, so can you send [me](https://community.parqet.com/u/e1ecc036) a message.

Yes, I have already pinged you there :)

2021-09-24 09:54 UTC, tobiasdrechsel commented on types/custom.d.ts
> +  foreignCurrency?: number | string;
You are right, I had to change the return type of `findFxRateAndForeignCurrency` from a union array to a tuple.

2021-09-24 10:01 UTC, tobiasdrechsel commented on src/index.js
> -pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;
I utilised the [webpack entry point](https://github.com/tobiasdrechsel/tresor-import/blob/eb014d34b935b3137be94d0a342b15736700d128/src/index.js#L2) from pdfs-dist where the [worker setup](https://github.com/mozilla/pdfjs-dist/blob/e9492b7a725ec4edd466880223474f4295a5fb45/webpack.js#L21) is already included.

2021-09-24 10:10 UTC, tobiasdrechsel commented on src/brokers/smartbroker.js
> + * @param {string[]} content
> The type of content can be page right?

done

> This can also applies for other usages of string[]

Yes of course `page` is just a typedef for `string[]`. I introduced it because I found it sometimes difficult to understand the meaning of `string[][]` with `page[]` it was more clear to me that one page consists of an string array and therefore multiple pages consist of an 2D string array.
While all instances of `string[]` could be replaced with `page` I think only the instances where `string[]` semantically refers to an actual `page` should be replaced. Because I have not yet fully wrapped my head around the semantic meaning of the code base I have probably missed a few instances.

2021-09-24 10:11 UTC, tobiasdrechsel commented on src/brokers/deutschebank.js
> + * @param {*} pagesFlat
done

2021-09-25 07:05 UTC, dredav submitted a review, later dismissed

2021-09-25 07:08 UTC, dredav commented on src/index.js
> -pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;
Good point. I muss that changed import of pdfjs 🙈

2021-09-25 07:08 UTC, dredav commented
Looks good. Could you solve the merge conflict (I merged today another PR already...)

2021-09-25 09:02 UTC, tobiasdrechsel commented
> Looks good. Could you solve the merge conflict (I merged today another PR already...)

done

2021-09-25 18:27 UTC, dredav approved these changes

2021-09-25 18:27 UTC, merged