feat(PP cash import)
tresorone/tresor-import pull request #4824
Opened 2021-12-14 03:24 UTC by JohnBra

2021-12-14 21:52 UTC, dredav requested changes

2021-12-14 21:52 UTC, dredav commented on tests/apps/portfolioPerformance/index.test.js
> +    fs.writeFileSync(activityFile, JSON.stringify(result.activities, null, 2));
I guess we should comment this out before we merge this PR :)

2021-12-14 21:52 UTC, dredav commented on src/apps/portfolioPerformance/utils.js
> +export const checkCashActivity = transaction => {
Minor: Should we rename this function because it's not a 'real check' function. What did you think about `normalizeCashActivity`?

2021-12-14 21:52 UTC, dredav commented on src/helper/index.js
> +  return validateCommons(activity);
Should we check here that the activity type is only one of: 'TransferIn', 'TransferOut'?

2021-12-14 22:46 UTC, JohnBra commented on tests/apps/portfolioPerformance/index.test.js
> +    fs.writeFileSync(activityFile, JSON.stringify(result.activities, null, 2));
si senor

2021-12-14 22:46 UTC, JohnBra commented on src/apps/portfolioPerformance/utils.js
> +export const checkCashActivity = transaction => {
thy will be done

2021-12-14 22:51 UTC, JohnBra commented on src/helper/index.js
> +  return validateCommons(activity);
I don't think so, since we are checking for `isCashActivity` before the call:
```js
// portfolioPerformance/index.js

const validate = activity => {
//...

  if (isCashActivity) {
    activity = validateCashActivity(activity);
  } else {
    activity = validateActivity(activity, true);
  }
//...
}
```

2021-12-15 21:04 UTC, dredav approved these changes
Nice 🎆 . Could you solve the merge conflicts?

2021-12-16 21:16 UTC, JohnBra commented
@dredav merge conflicts fixed

2021-12-20 22:01 UTC, dredav approved these changes

2021-12-20 22:02 UTC, merged