feature(quirion): Add also support to parse sell acivities
tresorone/tresor-import pull request #4854
Opened 2021-12-16 13:27 UTC by dredav

- [ ] Add sample from #245
- [ ] Adjust implementation to parse sell activities

2021-12-28 14:39 UTC, SirGibihm commented
Sadly, we have some merge conflicts despite respecting your chain of PRs. Seems like a small fix though

2021-12-28 14:39 UTC, SirGibihm requested changes
Merge is blocked, sadly

2021-12-28 18:12 UTC, dredav commented
@SirGibihm conflicts solved

2022-01-04 20:43 UTC, SirGibihm approved these changes

2022-01-04 20:43 UTC, merged