feature(sBroker): Add support for the new sbroker documents
tresorone/tresor-import pull request #4883
Opened 2021-12-20 15:39 UTC by dredav

- [ ] Resolves #4631
- [ ] Resolves #4761
- [ ] Resolves #4701

2022-01-04 20:49 UTC, SirGibihm requested changes

2022-01-04 20:49 UTC, SirGibihm commented on src/brokers/sbroker27.js
> +
Why do you declare these consts at the top instead of withing the activity? If you need them later on, you can just reference them from the activity

2022-01-04 20:49 UTC, SirGibihm commented on src/brokers/sbroker27.js
> +    delete activity.fxRate;
Could this be the same if condition as in foreignCurrency? It should only be set if you also set foreignCurrency, right?

Thinking about it, maybe its better to go explicit than implicit. What do you think?

2022-01-04 20:49 UTC, SirGibihm commented on src/brokers/sbroker27.js
> +  }
I think a switch case is neater here if we add further acitvities down the road

2022-01-05 18:51 UTC, dredav commented on src/brokers/sbroker27.js
> +    delete activity.fxRate;
:100:

2022-01-05 18:55 UTC, dredav commented on src/brokers/sbroker27.js
> +
hmm I agree for shares but not for amount. Assining activity.amount and than modifying the value later (with div of the fxRate) will be possible but IMO not so clean as modifying the amount first and set is as activity.amount.

2022-01-05 18:59 UTC, dredav commented on src/brokers/sbroker27.js
> +  }
hmm no. In this case we can't use a switch here for a switch we need to have as type (which will be parsed in this function). Outside of `getDocumentType` we should use a switch, like we did in `parsePages`.

2022-01-08 10:58 UTC, SirGibihm approved these changes

2022-01-08 10:58 UTC, merged