fix(finanzen zero): Parse `Mindermengenzuschlag` as fee
tresorone/tresor-import pull request #5219
Opened 2022-01-26 18:25 UTC by dredav

2022-02-08 12:00 UTC, SirGibihm requested changes
Maybe we got some PII that needs to be removed

2022-02-08 12:00 UTC, SirGibihm commented on tests/brokers/__mocks__/baaderbank/buy/2022_finanzen.net_IE00B8GKDB10.json
> +    "www.finanzen.net/zero",
Is this PII?

2022-02-09 20:05 UTC, dredav commented on tests/brokers/__mocks__/baaderbank/buy/2022_finanzen.net_IE00B8GKDB10.json
> +    "www.finanzen.net/zero",
@SirGibihm Good call! The phone numer? Not really, it's the number of the broker.

2022-03-10 07:29 UTC, SirGibihm approved these changes

2022-03-10 07:29 UTC, merged