feature(degiro): Add support for Degiro Switzerland with CHF Activities
tresorone/tresor-import pull request #5543
Opened 2022-03-08 21:46 UTC by dredav

- Fix #1921
- Fix #5316

2022-03-10 07:39 UTC, SirGibihm requested changes

2022-03-10 07:39 UTC, SirGibihm commented on src/brokers/degiro.js
> +};
Using a loop for this might work but my gut tells me this causes (performance) issues. See this thread for alternatives:
https://stackoverflow.com/questions/17369098/simplest-way-of-getting-the-number-of-decimals-in-a-number-in-javascript

If you think your solution is superior, please @ me again and I will approve your request

2022-03-10 22:07 UTC, dredav commented on src/brokers/degiro.js
> +};
@SirGibihm Thanks. I've changed the precision logic!

2022-03-31 21:21 UTC, dredav commented
PR is merged but Github can't set them to merged state because of too much linked issues. Thanks for nothing.

2022-03-31 21:21 UTC, closed without merging