fix,feat(ffb): Fix tax calculation, add support for Splittkauf, rename buy samples
tresorone/tresor-import pull request #5691
Opened 2022-03-28 16:12 UTC by Habemus42

Hi,
I've fixed the wrong tax calculation, added support for Splittkauf, which solves Issues #5562 and #5358.
Also I've renamed the buy examples for better uniformity.
I also added #4835 as an additional buy example.

2022-04-20 20:46 UTC, dredav requested changes

2022-04-20 20:46 UTC, dredav commented on src/brokers/ffb.js
> +      activity.tax = findTax(textArr, referenceLine);
Good catch!

2022-04-20 20:46 UTC, dredav commented on src/brokers/ffb.js
>        break;
Whats the possible error here? That we are trying to access and index which is out of range?

2022-04-20 20:46 UTC, dredav commented on src/brokers/ffb.js
> +      break;
Same point as above - which error will be catched here? Can't re prevent this error without a try-catch?

2022-04-20 20:47 UTC, dredav commented
Hey @Habemus42 👋🏻. First of all: Sorry for my late PR review but thanks for you PR and helping to make the FBB implementation better!  I've only have one (two) question which we should be resolve before mergin this PR.

2022-04-20 22:03 UTC, Habemus42 commented on src/brokers/ffb.js
>        break;
You are right, because there is a fixed number of lines to be searched for "Transaktionskosten", startLine+line can become larger than textArr.length. This is now done by an additional condition for the top end of the for loop.
Additionally I've reduced the fixed number of lines to be searched from 45 to 40, acutally 36 is already enough for all my examples.

2022-04-20 22:03 UTC, Habemus42 commented on src/brokers/ffb.js
> +      break;
see above

2022-04-20 22:06 UTC, Habemus42 reviewed
Try-catch removed.

2022-04-20 22:10 UTC, Habemus42 commented
Build failing seems not be caused by my changes.

2022-04-21 05:26 UTC, dredav approved these changes

2022-04-21 05:30 UTC, dredav approved these changes

2022-04-21 05:32 UTC, merged