[comdirect] Add support for `Bonifikation` which reduce the payed amount
tresorone/tresor-import pull request #957
Opened 2021-01-12 20:43 UTC by dredav

- Fix #863
- Add sample from #863 as a new test case

2021-01-13 16:33 UTC, SirGibihm requested changes

2021-01-13 16:33 UTC, SirGibihm commented on tests/brokers/comdirect.test.js
> +        fee: 0,
In most other cases we have a bonifcation as a negtive fee. IMO all brokers should be in line regarding this question.

2021-01-13 16:33 UTC, SirGibihm commented on src/brokers/comdirect.js
> +    }
IMO this should be part of the fee calulation as well, see below.

2021-01-13 17:45 UTC, dredav commented on tests/brokers/comdirect.test.js
> +        fee: 0,
Oh good catch. So the bonifcation is a negative fee and the amount will be the current amount + bonifcation.

2021-01-28 09:27 UTC, SirGibihm approved these changes

2021-01-28 09:27 UTC, merged