[deutschebank] Basic Support for new broker + Documentation on supported brokers (#982) (major)
tresorone/tresor-import pull request #996
Opened 2021-01-14 22:09 UTC by SirGibihm

Added basic support for the broker *Deutsche Bank*. Also added a new section for documentation that explains which broker is supported and which files can be imported. 
* Added new Documenation
* Added Testcases from #982  (Fixes #982)
* Implemented a new broker Deutsche Bank
* **Currently only Dividends are supported**
* Added support for transaction Reports  (Fix #810)
  * Can only parse `Buy` at the moment. `Sell` was not in the documents and `Dividends` cant be supported
* Added support for Depot Status (Fix #796)
* Sell Documents must be ignored sadly, Fix #1029 

The testfiles for the `Buy` and `Sell` operations can not be parsed due to .pdf parsing issues of `pdfjs`. Fingers crossed it is only due to a singularity and other `Buy` and `Sell` operations can be parsed once we get the testfiles.

EDIT: Its not. They're just dickered

2021-01-16 11:15 UTC, dredav requested changes

2021-01-16 11:15 UTC, dredav commented on src/brokers/deutschebank.js
> +    txIdx = findNextIdx(content, transactionTypes, txIdx + 1);
Why not setting `txIdx` in the first line of the while loop? So we only need one call to `findNextIdx ` and `txIdx` can be initialized with `0`.

2021-01-16 11:15 UTC, dredav commented on src/brokers/deutschebank.js
> +  const transactionTypes = ['Kauf', 'Dividende /'];
Why searching for `'Dividende /'` when it's not supported yet?

2021-01-16 14:26 UTC, SirGibihm commented on README.md
> +- [Deutsche Bank](docs/supportedBrokers/deutschebank.md)
Honestly, I totally forgot this page exists. Will adapt accordingly and reference the detailed table  in `docs/implementations.md`

2021-01-16 14:35 UTC, SirGibihm commented on src/helper/index.js
> +export function regexMatchIndex(content, regex, offset = 0) {
Renamed to `findNextLineIndexByRegex` to keep it short

2021-01-16 14:36 UTC, SirGibihm commented on src/brokers/deutschebank.js
> +  const transactionTypes = ['Kauf', 'Dividende /'];
Removed it

2021-01-16 14:40 UTC, SirGibihm commented on src/brokers/deutschebank.js
> +    txIdx = findNextIdx(content, transactionTypes, txIdx + 1);
Fixed

2021-01-24 10:16 UTC, dredav submitted a review, later dismissed
🚀

2021-01-24 10:22 UTC, dredav approved these changes

2021-01-24 10:30 UTC, merged